/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetDictApiDictDetailGetParams
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * @summary List Dicts
 */
export const listDictsApiDictGet = (
    
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/dict/`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Get Dict
 */
export const getDictApiDictDetailGet = (
    params: GetDictApiDictDetailGetParams,
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/dict/detail`, method: 'GET',
        params
    },
      options);
    }
  export type ListDictsApiDictGetResult = NonNullable<Awaited<ReturnType<typeof listDictsApiDictGet>>>
export type GetDictApiDictDetailGetResult = NonNullable<Awaited<ReturnType<typeof getDictApiDictDetailGet>>>
