/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  UserResponse
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * @summary Get All
 */
export const getAllApiUserGet = (
    
 options?: SecondParameter<typeof customAxiosInstance<UserResponse[]>>,) => {
      return customAxiosInstance<UserResponse[]>(
      {url: `/api/user/`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Get By Id
 */
export const getByIdApiUserUserIdGet = (
    userId: number,
 options?: SecondParameter<typeof customAxiosInstance<UserResponse>>,) => {
      return customAxiosInstance<UserResponse>(
      {url: `/api/user/${userId}`, method: 'GET'
    },
      options);
    }
  export type GetAllApiUserGetResult = NonNullable<Awaited<ReturnType<typeof getAllApiUserGet>>>
export type GetByIdApiUserUserIdGetResult = NonNullable<Awaited<ReturnType<typeof getByIdApiUserUserIdGet>>>
