/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * 返回用户：包含 id，排除 password
 */
export interface UserResponse {
  /**
   * 用户名
   * @minLength 2
   * @maxLength 50
   */
  name: string;
  /**
   * 年龄
   * @exclusiveMinimum 0
   * @exclusiveMaximum 150
   */
  age: number;
  /** 用户ID */
  id: number;
}
